=== OlivierLD/olivsoft-swing/sailfax/fax-data-v2.xsd
<?xml version="1.0" encoding="windows-1252" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.fax-data.org"
            xmlns:fax="http://www.fax-data.org"
            elementFormDefault="qualified">
  <xsd:element name="fax-data">
    <xsd:annotation>
      <xsd:documentation>
        For SailFax
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="bulletins" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:all>
              <xsd:element name="stations">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="station" maxOccurs="unbounded">
                      <xsd:complexType>
                        <xsd:all>
                          <xsd:element name="name" type="xsd:string"/>
                          <xsd:element name="frequencies">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element name="frequency" minOccurs="1"
                                             maxOccurs="unbounded">
                                  <xsd:complexType>
                                    <xsd:all>
                                      <xsd:element name="freq"
                                                   type="xsd:decimal"/>
                                      <xsd:element name="times"
                                                   type="xsd:string"
                                                   minOccurs="0"/>
                                      <xsd:element name="emission"
                                                   type="xsd:string"
                                                   minOccurs="0"/>
                                      <xsd:element name="power"
                                                   type="xsd:string"
                                                   minOccurs="0"/>
                                    </xsd:all>
                                    <xsd:attribute name="freq-type"
                                                   type="fax:mode-type"
                                                   use="required"/>
                                  </xsd:complexType>
                                </xsd:element>
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:all>
                        <xsd:attribute name="call-sign" type="xsd:string"/>
                      </xsd:complexType>
                      <xsd:key name="map-key">
                        <xsd:selector xpath="./fax:map-areas/fax:map-area"/>
                        <xsd:field xpath="@id"/>
                      </xsd:key>
                      <xsd:keyref name="map-refer" refer="fax:map-key">
                        <xsd:selector xpath="./fax:transmissions/fax:transmission/fax:map-zone"/>
                        <xsd:field xpath="."/>
                      </xsd:keyref>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="bulletins-data">
                <xsd:complexType>
                  <xsd:all>
                    <xsd:element name="map-areas">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="map-area" maxOccurs="unbounded">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element name="top" type="xsd:string"/>
                                <xsd:element name="bottom" type="xsd:string"/>
                                <xsd:element name="left" type="xsd:string"/>
                                <xsd:element name="right" type="xsd:string"/>
                              </xsd:sequence>
                              <xsd:attribute name="id" type="xsd:string"/>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="transmissions">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="transmission"
                                       maxOccurs="unbounded">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element name="starts"
                                             type="fax:start-stop-type"/>
                                <xsd:element name="stops"
                                             type="fax:start-stop-type"/>
                                <xsd:element name="rpm-ioc" type="xsd:string"
                                             minOccurs="0"/>
                                <xsd:element name="mode" type="fax:mode-type"
                                             maxOccurs="1" minOccurs="1"/>
                                <xsd:element name="content" type="xsd:string"
                                             minOccurs="1"/>
                                <xsd:element name="valid-time"
                                             type="xsd:string" minOccurs="0"/>
                                <xsd:element name="map-zone" type="xsd:string"
                                             minOccurs="0"/>
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:all>
                </xsd:complexType>
              </xsd:element>
            </xsd:all>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:simpleType name="mode-type">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="fax"/>
      <xsd:enumeration value="sitor"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="start-stop-type">
    <xsd:restriction base="xsd:string">
      <xsd:length value="5"/>
      <xsd:pattern value="\d{2}:\d{2}"/>
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== OlivierLD/olivsoft-swing/release/all-scripts/pac-fax-data.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  The <starts> element is the actual start of the transmission.
  The Fax program will search for start tone, beginning two minutes 
  BEFORE the listed start time, if not found by the stop time then 
  fax is aborted.  
  In other words, the stop is not the end of the transmission.
  
  Example:
  If you have :
    <starts>10:00</starts>
    <stops>10:03</stops>
  the fax program will be searching for the start signal as soon as 09:58.
  If the start signal is found before 10:03, the fax will be received 
  completely, finished with a stop signal.
  If no start signal has been received by 10:03, then the fax is 
  aborted.
  
  Olivier Le Diouris, January 2007.
  olivier@lediouris.net
  wdc7278@sailmail.com
  http://donpedro.lediouris.net
  -->
<fax-data xmlns="http://www.fax-data.org"
          xmlns:xsi="http://www.w3.org/XML/1998/namespace"
          xsi:schemaLocation="http://www.fax-data.org fax-data-v2.xsd">
  <bulletins>
    <stations>
      <station call-sign="NMC">
        <name>San Francisco (Pt. Reyes)</name>
        <frequencies>
          <frequency freq-type="fax">
            <freq>4346</freq>
            <times>NIGHT</times>
            <emission>F3C</emission>
            <power>4 KW</power>
          </frequency>
          <frequency freq-type="fax">
            <freq>8682</freq>
            <times>CONTINOUS</times>
            <emission>F3C</emission>
            <power>4 KW</power>
          </frequency>
          <frequency freq-type="fax">
            <freq>12730</freq>
            <times>CONTINOUS</times>
            <emission>F3C</emission>
            <power>4 KW</power>
          </frequency>
          <frequency freq-type="fax">
            <freq>17151.2</freq>
            <times>CONTINOUS</times>
            <emission>F3C</emission>
            <power>4 KW</power>
          </frequency>
          <frequency freq-type="fax">
            <freq>22527</freq>
            <times>DAY</times>
            <emission>F3C</emission>
            <power>4 KW</power>
          </frequency>
          <frequency freq-type="sitor">
            <freq>8416.5</freq>
            <emission>SITOR</emission>
          </frequency>
          <frequency freq-type="sitor">
            <freq>16806.5</freq>
            <emission>SITOR</emission>
          </frequency>
        </frequencies>
      </station>
    </stations>
    <bulletins-data>
      <map-areas>
        <map-area id="1">
          <top>70 N</top>
          <bottom>20 N</bottom>
          <left>135 E</left>
          <right>115 W</right>
        </map-area>
        <map-area id="2">
          <top>70 N</top>
          <bottom>20 N</bottom>
          <left>175 W</left>
          <right>115 W</right>
        </map-area>
        <map-area id="3">
          <top>70 N</top>
          <bottom>20 N</bottom>
          <left>135 E</left>
          <right>175 W</right>
        </map-area>
        <map-area id="4">
          <top>30 N</top>
          <bottom>20 S</bottom>
          <left>145 W</left>
          <right>72 W</right>
        </map-area>
        <map-area id="5">
          <top>55 N</top>
          <bottom>5 N</bottom>
          <left>180 W</left>
          <right>0 E</right>
        </map-area>
        <map-area id="6">
          <top>60 N</top>
          <bottom>23 N</bottom>
          <left>150 W</left>
          <right>0 E</right>
        </map-area>
        <map-area id="7">
          <top>32 N</top>
          <bottom>5 N</bottom>
          <left>130 W</left>
          <right>0 E</right>
        </map-area>
        <map-area id="8">
          <top>62 N</top>
          <bottom>18 N</bottom>
          <left>157 W</left>
          <right>0 E</right>
        </map-area>
        <map-area id="9">
          <top>53 N</top>
          <bottom>40 N</bottom>
          <left>136 W</left>
          <right>0 E</right>
        </map-area>
        <map-area id="10">
          <top>40 N</top>
          <bottom>0 N</bottom>
          <left>180 W</left>
          <right>80 W</right>
        </map-area>
      </map-areas>
      <transmissions>
        <transmission>
          <starts>00:15</starts>
          <stops>00:45</stops>
          <mode>FEC</mode>
          <content>sitor weather</content>
        </transmission>
        <transmission>
          <starts>01:40</starts>
          <stops>01:43</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>Test Pattern</content>
        </transmission>
        <transmission>
          <starts>14:00</starts>
          <stops>14:03</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>Test Pattern</content>
        </transmission>
        <transmission>
          <starts>01:43</starts>
          <stops>01:46</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>NE Pacific Goes IR Satellite Image</content>
          <map-zone>6</map-zone>
        </transmission>
        <transmission>
          <starts>14:03</starts>
          <stops>14:06</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>NE Pacific Goes IR Satellite Image</content>
          <map-zone>6</map-zone>
        </transmission>
        <transmission>
          <starts>01:54</starts>
          <stops>01:57</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>Pacific Goes IR Satellite Image</content>
          <map-zone>5</map-zone>
        </transmission>
        <transmission>
          <starts>14:14</starts>
          <stops>14:17</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>Pacific Goes IR Satellite Image</content>
          <map-zone>5</map-zone>
        </transmission>
        <transmission>
          <starts>02:05</starts>
          <stops>02:08</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>Tropical Sea State Analysis</content>
          <map-zone>4</map-zone>
        </transmission>
        <transmission>
          <starts>14:25</starts>
          <stops>14:28</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>Tropical Sea State Analysis</content>
          <map-zone>4</map-zone>
        </transmission>
        <transmission>
          <starts>02:15</starts>
          <stops>02:18</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>Tropical 24h Wind/Wave Forecast</content>
          <map-zone>4</map-zone>
        </transmission>
        <transmission>
          <starts>14:35</starts>
          <stops>14:38</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>Tropical 24h Wind/Wave Forecast</content>
          <map-zone>4</map-zone>
        </transmission>
        <transmission>
          <starts>02:25</starts>
          <stops>02:28</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>Tropical 48h Wind/Wave Forecast</content>
          <map-zone>4</map-zone>
        </transmission>
        <transmission>
          <starts>02:35</starts>
          <stops>02:38</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>Tropical 72h Wind/Wave Forecast</content>
          <map-zone>4</map-zone>
        </transmission>
        <transmission>
          <starts>02:45</starts>
          <stops>02:48</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>500Mb Analysis</content>
          <map-zone>1</map-zone>
        </transmission>
        <transmission>
          <starts>14:45</starts>
          <stops>14:48</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>500Mb Analysis</content>
          <map-zone>1</map-zone>
        </transmission>
        <transmission>
          <starts>02:55</starts>
          <stops>02:58</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>Sea State Analysis, Wind/Wave Analysis</content>
          <map-zone>1</map-zone>
        </transmission>
        <transmission>
          <starts>14:55</starts>
          <stops>14:58</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>Sea State Analysis, Wind/Wave Analysis</content>
          <map-zone>1</map-zone>
        </transmission>
        <transmission>
          <starts>03:05</starts>
          <stops>03:08</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>Prelim Surface Analysis (Part 1 - NE Pac)</content>
          <map-zone>2</map-zone>
        </transmission>
        <transmission>
          <starts>15:05</starts>
          <stops>15:08</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>Prelim Surface Analysis (Part 1 - NE Pac)</content>
          <map-zone>2</map-zone>
        </transmission>
        <transmission>
          <starts>03:18</starts>
          <stops>03:21</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>Prelim Surface Analysis (Part 2 - NW Pac)</content>
          <map-zone>3</map-zone>
        </transmission>
        <transmission>
          <starts>15:18</starts>
          <stops>15:21</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>Prelim Surface Analysis (Part 2 - NW Pac)</content>
          <map-zone>3</map-zone>
        </transmission>
        <transmission>
          <starts>03:31</starts>
          <stops>03:34</stops>
          <rpm-ioc>120/576</rpm-ioc>
          <mode>fax</mode>
          <content>Final Surface Analysis (Part 1 - NE Pac)</content>
          <map-zone>2</map-zone>
        </transmission>
        <transmission>
          <starts>15:31</starts>
          <stops>15:34</stops>
          <rpm-ioc>120/576</rpm-ioc>
